### ISSUE TITLE
Deleting a collection throws an error

### ISSUE THREAD

**Issue by cncoleman** [sul-dlss/mirador_sul#111]
<img width="763" alt="screen shot 2017-04-26 at 1 06 08 pm" src="https://cloud.githubusercontent.com/assets/288005/25454451/5033950c-2a81-11e7-89e8-7759a4dae889.png">

**Comment by cncoleman** [comment]
It seems to happen only when deleting a collection that has a workspace. Deleting a collection with manifests but no workspaces does not seem to produce the error.

**Comment by mejackreed** [comment]
Potentially related to: old.jack-reed.com

**Comment by jkeck** [comment]
Looks like the foreign key issue again: https://app.honeybadger.io/projects/51654/faults/33222324#notice-summary

#81 was supposed to address that (and I think was verified locally by @drh-stanford).

**Comment by csbailey5t** [comment]
@cncoleman Was this on the prod server? If so, that hasn't been updated with the foreign key fix and should be broken. It will be fixed once we push the updated code to prod.

**Comment by cncoleman** [comment]
@csbailey5t That's right (as we discussed in person). Thanks
