### ISSUE TITLE
Pull in font that was used in gh-pages for the branding

### ISSUE THREAD

**Issue by csbailey5t** [sul-dlss/mirador_sul#43]
We need to pull in the font from gh-pages for the branding in the Rails app

Font: Yanone Kaffeesatz

Found in Google Fonts. https://fonts.google.com/specimen/Yanone+Kaffeesatz

E.g. `<link href="http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:300,200" rel="stylesheet" type="text/css">`

**Comment by mejackreed** [comment]
Is the font to be used throughout? Or only for a title?

**Comment by csbailey5t** [comment]
According to @cncoleman it should be used for the mirador@stanford brand is used, so in the header and on the home page right now. I don't think that will be the font for the rest of the text, though.
