### ISSUE TITLE
Add links to Collections & Workspaces in the nav bar

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/mirador_sul#44]
This could be right justified near the Logout link.

Any opinion on `My Collections` vs simply `Collections`?

**Comment by versae** [comment]
Eventually, it might be useful to distinguish between collections you own and collections you have access to. For now though I'd go with `Collections`.

**Comment by versae** [comment]
Actually, it looks weird to have `My Collections` and then `My Workspaces`. So I'll strip the `My` part.
