### ISSUE TITLE
Workspace Show View Changes

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/mirador_sul#49]
- [ ] ~Move Workspace title into mirador viewer~
  * Being taken care of in another PR
- [x] Remove Back button
- [x] Style mirador viewer to take up the entire height/width of the page content area (retain red nav bar)
- [x] Instantiate Mirador viewer for a New Workspaces with the load window open/initialized.

Note: We want to experiment with a max-width on the mirador load-window.

**Comment by versae** [comment]
I think it'll be better to wait until #35 gets merged.
