### ISSUE TITLE
Workspaces index view

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/mirador_sul#52]
- [x] Turn workspace lists into some sort of tiles (isotope or masonry?)
- [x] Add a placeholder image
- [x] Turn actions links into buttons
- [x] Add description (if we have it)

**Comment by aeschylus** [comment]
@jkeck Would love to pair on this when you get a minute.

**Comment by versae** [comment]
Re: isotope vs masonry:
- Isotope.js: [11.4m Google](https://www.google.com/?q=isotope+js), [555 SO](http://stackoverflow.com/search?q=isotope+js), [March 8, 2017 last commit](https://github.com/metafizzy/isotope), [free for non comercial use](http://isotope.metafizzy.co/license.html)
- Masonry.js: [564k Google](https://www.google.com/?gws_rd=ssl#q=masonry+js), [976 SO](http://stackoverflow.com/search?q=masonry+js), [Aug 29, 2016 last commit](https://github.com/desandro/masonry), [MIT license](http://masonry.desandro.com/#mit-license)
