### ISSUE TITLE
Implement SOLR backend for simpleAnnotationServer at Stanford

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/mirador_sul#6]

**Comment by blalbrit** [comment]
@eefahy - should we set this up on solr-cloud? If so, can we get a core for -test/stage and -prod?

**Comment by drh-stanford** [comment]
To configure Solr and SAS see https://github.com/glenrobson/SimpleAnnotationServer/blob/master/doc/Solr.md

**Comment by drh-stanford** [comment]
See PR https://github.com/sul-dlss/sul-solr-configs/pull/97
