### ISSUE TITLE
CSS removes padding from "change layout" interface elements.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/mirador_sul#61]

**Comment by aeschylus** [comment]
![screen shot 2017-04-06 at 11 45 11](https://cloud.githubusercontent.com/assets/145874/24770355/8707f488-1abe-11e7-9778-b0972dfb0d28.png)

**Comment by mejackreed** [comment]
Can you confirm that this is happening on latest master? I cannot recreate.

<img width="435" alt="screen shot 2017-04-07 at 10 21 47 am" src="https://cloud.githubusercontent.com/assets/1656824/24804320/0e909e10-1b7c-11e7-8898-793ca3912bba.png">

**Comment by aeschylus** [comment]
Yep, no longer happening.
