### ISSUE TITLE
CSS changes link colour on slot close button

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/mirador_sul#63]
![screen shot 2017-04-06 at 11 46 52](https://cloud.githubusercontent.com/assets/145874/24770451/d6b14de0-1abe-11e7-829d-0cf45e661c25.png)

**Comment by mejackreed** [comment]
Can you confirm that this is still happening with latest master? I cannot recreate.

**Comment by csbailey5t** [comment]
I also cannot recreate.

**Comment by aeschylus** [comment]
No longer happening.
