### ISSUE TITLE
Hook up rubocop to build/test suite

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/mirador_sul#73]
Noticing some style violations creep their way into the codebase.  We should hook rubocop to fail the build so we don't continue to introduce more.

**Comment by drh-stanford** [comment]
The specs have 100+ violations. Will clean this up and add todo items

**Comment by drh-stanford** [comment]
Having an issue where `bundle exec rubocop` works fine but `bundle exec rake rubocop` finds errors.

**Comment by drh-stanford** [comment]
`rake rubocop` adds rails and rspec tests, so I've added corrections/todos for those in #87
